name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - uses: actions/checkout@v4
    - name: 'Build Inventory Image'
      run: |
        docker build . --tag ghcr.io/iraitzm/dsptbil2025-streamlit-iris:$(date +%s)
        docker push ghcr.io/iraitzm/dsptbil2025-streamlit-iris:$(date +%s)
